
  CREATE TABLE "COMMISSIONS" 
   (	"COMMISSION_SUM" VARCHAR2(20), 
	"PAYMENT_DATE" VARCHAR2(20), 
	"AGENT_ID" NUMBER NOT NULL ENABLE
   ) ;

  ALTER TABLE "COMMISSIONS" ADD CONSTRAINT "COMMISSIONS_AGENT" FOREIGN KEY ("AGENT_ID")
	  REFERENCES "AGENTS" ("AGENT_ID") ENABLE;

  CREATE INDEX "IDX_COMMISSIONS_AGENT_ID" ON "COMMISSIONS" ("AGENT_ID") 
  ;