
  CREATE TABLE "DBTOOLS$EXECUTION_HISTORY" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"HASH" CLOB, 
	"CREATED_BY" VARCHAR2(255), 
	"CREATED_ON" TIMESTAMP (6) WITH TIME ZONE, 
	"UPDATED_BY" VARCHAR2(255), 
	"UPDATED_ON" TIMESTAMP (6) WITH TIME ZONE, 
	"STATEMENT" CLOB, 
	"TIMES" NUMBER, 
	 CONSTRAINT "DBTOOLS$EXECUTION_HISTORY_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;