
  CREATE TABLE "EMPLOYEES" 
   (	"EMPLOYEE_ID" NUMBER, 
	"FIRST_NAME" VARCHAR2(50), 
	"LAST_NAME" VARCHAR2(50), 
	"ROLE_ID" NUMBER, 
	 PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "EMPLOYEES" ADD FOREIGN KEY ("ROLE_ID")
	  REFERENCES "ROLES" ("ROLE_ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "EMPLOYEES_BEFORE_INSERT" 
BEFORE INSERT ON employees
FOR EACH ROW
BEGIN
  IF :NEW.EMPLOYEE_ID IS NULL THEN
    SELECT employees_seq.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM dual;
  END IF;
END;
/
ALTER TRIGGER "EMPLOYEES_BEFORE_INSERT" ENABLE;