
  CREATE TABLE "ORDERS" 
   (	"ORDER_ID" NUMBER, 
	"ORDER_DATE" DATE, 
	"EMPLOYEE_ID" NUMBER, 
	"PRICE_SUM" NUMBER(10,2), 
	"COMMISSION_ORDER" NUMBER, 
	 PRIMARY KEY ("ORDER_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "ORDERS" ADD FOREIGN KEY ("EMPLOYEE_ID")
	  REFERENCES "EMPLOYEES" ("EMPLOYEE_ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "ORDERS_BEFORE_INSERT" 
BEFORE INSERT ON Orders
FOR EACH ROW
BEGIN
  IF :NEW.order_id IS NULL THEN
    SELECT orders_seq.NEXTVAL INTO :NEW.order_id FROM dual;
  END IF;
END;
/
ALTER TRIGGER "ORDERS_BEFORE_INSERT" ENABLE;