
  CREATE TABLE "PRODUCTS" 
   (	"PRODUCT_ID" NUMBER, 
	"NAME" VARCHAR2(100), 
	"PRICE" NUMBER(10,2), 
	"CATEGORY_ID" NUMBER, 
	 PRIMARY KEY ("PRODUCT_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "PRODUCTS" ADD FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "CATEGORIES" ("CATEGORY_ID") ENABLE;