
  CREATE TABLE "SALARIES" 
   (	"SALARY_ID" NUMBER(10,2), 
	"EMPLOYEE_ID" NUMBER, 
	"SALARY_MONTH" DATE, 
	"SALARY_SUM" NUMBER, 
	 PRIMARY KEY ("SALARY_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "SALARIES" ADD FOREIGN KEY ("EMPLOYEE_ID")
	  REFERENCES "EMPLOYEES" ("EMPLOYEE_ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "SALARIES_BEFORE_INSERT" 
BEFORE INSERT ON salaries
FOR EACH ROW
BEGIN
  IF :NEW.salary_id IS NULL THEN
    SELECT salaries_seq.NEXTVAL INTO :NEW.salary_id FROM dual;
  END IF;
END;
/
ALTER TRIGGER "SALARIES_BEFORE_INSERT" ENABLE;